name: build

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Use Node.js 16.13.2
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.2

      - name: Build
        run: |
          npm ci
          npm run build
